version: '3'

services:
  api:
    build: .
    image: canersezgin/node-mongo-redis
    environment: 
      - NODE_ENV=development
      - PORT=5001
    env_file: 
      - .env
    ports:
      - '80:5001'
    volumes: 
      - .:/home/node/app
    command: 
      - npm 
      - run
      - dev

networks: 
  node_mongo_redis:
